# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('location_lon', models.FloatField()),
                ('location_lat', models.FloatField()),
                ('current_track_id', models.CharField(default=-1, max_length=100)),
                ('token', models.CharField(default=-1, max_length=200)),
                ('preview_url', models.URLField(default=-1)),
                ('playlist_id', models.CharField(default=-1, max_length=100)),
                ('nearest_users', models.ManyToManyField(related_name='_user_nearest_users_+', to='users.User')),
            ],
        ),
    ]
