# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
            ],
        ),
    ]
