# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171125_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_track_id',
            field=models.CharField(default=-1, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='nearest_users',
            field=models.ManyToManyField(related_name='_user_nearest_users_+', to='users.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
