# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171125_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preview_url',
            field=models.URLField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=-1, max_length=200),
        ),
    ]
