# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171125_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playlist_id',
            field=models.CharField(default=-1, max_length=100),
        ),
    ]
