# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171126_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nearest_users',
        ),
        migrations.AddField(
            model_name='user',
            name='nearest_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
