# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_x',
            new_name='location_lat',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_y',
            new_name='location_lon',
        ),
    ]
